### ISSUE TITLE
SMB app could change its notification about sharing access violation.

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#53]
When many users open then same Microsoft Word document from a SMB folder then they see a following things:
1) Users from Windows PC have not any notifications and can read or write text without errors (yes, they are erase text from other users).
2) Users from Chromebook have an error message from SMB app and can not write text even if other users only read this document (see picture below).

This behavior destructing a Chromebook user experience despite this behavior is more better in cooperative mode than Windows behavior.
I suggest to change this special error message for something like this:
You can not edit document right now because someone else open it for editing.
Please, move a document to Google Drive for enabling concurrent editing capabilities.

![concurently edition](https://cloud.githubusercontent.com/assets/12710354/8124837/5a01a29a-10e8-11e5-877a-9ff1b847490c.png)

**Comment by yoichiro** [comment]
@AndreyLavrov Hmm... Well, I thought that this issue will occur, because the current version doesn't support all commands regarding the "File locking". Yes, probably, I have to implement the logic to lock the file before opening and etc...

**Comment by yoichiro** [comment]
@AndreyLavrov I have already implement SMB2 protocol to my app. Well, does this issue occur on the SMB2? Sorry, I'm not sure about this issue...

**Comment by AndreyLavrov** [comment]
Test lab setup:
1) Domain: Microsoft Active Directory (WANCASTLE domain)
2) Server: File server powered by Windows Server 2008 R2 with SMB2 protocol enabled
3) Cromebook: LG Chromebase (Version 46.0.2490.71 (64-bit) Platform 7390.61.0 (Official Build) stable-channel monroe Firmware Google_Monroe.4921.17.0)
4) Windows: Windows 7 (64-bit Eng) with Microsoft Office 2010 suite
5) FS4W: "File System for Windows" application v.2.5.0 

FS4W have these behaviour:
1) When the same document have opened from Chromebook and from Windows after then Chromebook rise 103 error from FS4W application.
2) When the same document have opened from Windows and from Chromebook after then Chromebook showing a last saved state of the document without any errors. If you try to edit document from Chromebook than you see 103 error from FS4W application.

**Comment by AndreyLavrov** [comment]
TaskQueue: addTask - Call consume task: length=1
TaskQueue: consumeTask - execute task: length=1
onTruncateRequested Object {filePath: "/Docs/Installation Guide.docx", fileSystemId: "cifsfs://WAN-MON01:445/WANCASTLE@SMBDomainUser/Public", length: 0, requestId: 286}
Client#truncate
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: 137…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 200, packetHelper_: PacketHelper}
writePacket
FE53 4D42 4000 0100 0000 0000 0500 0100  .SMB@...........
0000 0000 0000 0000 A200 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3900 0000 0200 0000 0000 0000 0000 0000  9...............
0000 0000 0000 0000 8900 0000 8000 0000  ................
0700 0000 0100 0000 4000 0000 7800 3800  ........@...x.8.
B000 0000 1800 0000 4400 6F00 6300 7300  ........D.o.c.s.
5C00 4900 6E00 7300 7400 6100 6C00 6C00  .I.n.s.t.a.l.l.
6100 7400 6900 6F00 6E00 2000 4700 7500  a.t.i.o.n. .G.u.
6900 6400 6500 2E00 6400 6F00 6300 7800  i.d.e...d.o.c.x.
0000 0000 1000 0400 0000 0000 0000 0000  ................
4D78 4163 0000 0000  MxAc....

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 184
FE53 4D42 4000 0100 0000 0000 0500 0100  .SMB@...........
0100 0000 0000 0000 A200 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
5900 0000 0100 0000 114E DE09 D2A4 D001  Y........N......
6CE1 D946 D8A4 D001 CC7E 1679 AC0F D101  l..F.....~.y....
CC7E 1679 AC0F D101 0080 0000 0000 0000  .~.y............
FA40 0000 0000 0000 2000 0000 0000 0000  .@...... .......
8501 0000 2000 0000 A100 0000 FFFF FFFF  .... ...........
9800 0000 2000 0000 0000 0000 1000 0400  .... ...........
0000 1800 0800 0000 4D78 4163 0000 0000  ........MxAc....
0000 0000 FF01 1F00  ........

Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateResponse {types_: Types, structureSize_: 89, oplockLevel_: 0, createAction_: 1, creationTime_: Fri Jun 12 2015 08:38:40 GMT+0300 (MSK)…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
ReadRequest {types_: Types, length_: 0, offset_: 0, fileId_: Uint8Array[16]}
writePacket
FE53 4D42 4000 0100 0000 0000 0800 0100  .SMB@...........
0000 0000 0000 0000 A300 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3100 5000 0000 0000 0000 0000 0000 0000  1.P.............
8501 0000 2000 0000 A100 0000 FFFF FFFF  .... ...........
0100 0000 0000 0000 0000 0000 0000 0000  ................
00 .

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 73
FE53 4D42 4000 0100 1100 00C0 0800 0100  .SMB@...........
0100 0000 0000 0000 A300 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 0000 0000 00 .........

Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 17…}
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CloseRequest {types_: Types, fid_: Uint8Array[16], flags_: 0}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 88, packetHelper_: PacketHelper}
writePacket
FE53 4D42 4000 0100 0000 0000 0600 0100  .SMB@...........
0000 0000 0000 0000 A400 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
1800 0000 0000 0000 8501 0000 2000 0000  ............ ...
A100 0000 FFFF FFFF  ........

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 124
FE53 4D42 4000 0100 0000 0000 0600 0100  .SMB@...........
0100 0000 0000 0000 A400 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3C00 0000 0000 0000 0000 0000 0000 0000  <...............
0000 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000 0000 0000  ................
0000 0000 0000 0000 0000 0000  ............

Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: 415…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 200, packetHelper_: PacketHelper}
writePacket
FE53 4D42 4000 0100 0000 0000 0500 0100  .SMB@...........
0000 0000 0000 0000 A500 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3900 0000 0200 0000 0000 0000 0000 0000  9...............
0000 0000 0000 0000 9F01 0000 8000 0000  ................
0700 0000 0500 0000 4000 0000 7800 3800  ........@...x.8.
B000 0000 1800 0000 4400 6F00 6300 7300  ........D.o.c.s.
5C00 4900 6E00 7300 7400 6100 6C00 6C00  .I.n.s.t.a.l.l.
6100 7400 6900 6F00 6E00 2000 4700 7500  a.t.i.o.n. .G.u.
6900 6400 6500 2E00 6400 6F00 6300 7800  i.d.e...d.o.c.x.
0000 0000 1000 0400 0000 0000 0000 0000  ................
4D78 4163 0000 0000  MxAc....

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 73
FE53 4D42 4000 0100 0301 0000 0500 0100  .SMB@...........
0300 0000 0000 0000 A500 0000 0000 0000  ................
2500 0800 0000 0000 7500 0000 0004 0000  %.......u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 0000 0000 00 .........

103: UNKNOWN
console.trace()
FAILED
TaskQueue: consumeTask - queue: empty
TaskQueue: addTask - Call consume task: length=1
TaskQueue: consumeTask - execute task: length=1
onOpenFileRequested Object {filePath: "/Docs/Installation Guide.docx", fileSystemId: "cifsfs://WAN-MON01:445/WANCASTLE@SMBDomainUser/Public", mode: "WRITE", requestId: 287}
TaskQueue: consumeTask - queue: empty
TaskQueue: addTask - Call consume task: length=1
TaskQueue: consumeTask - execute task: length=1
onWriteFileRequested Object {data: ArrayBuffer, fileSystemId: "cifsfs://WAN-MON01:445/WANCASTLE@SMBDomainUser/Public", offset: 0, openRequestId: 287, requestId: 288}
Client#writeFile
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: 415…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 200, packetHelper_: PacketHelper}
writePacket
FE53 4D42 4000 0100 0000 0000 0500 0100  .SMB@...........
0000 0000 0000 0000 A600 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3900 0000 0200 0000 0000 0000 0000 0000  9...............
0000 0000 0000 0000 9F01 0000 8000 0000  ................
0700 0000 0300 0000 4000 0000 7800 3800  ........@...x.8.
B000 0000 1800 0000 4400 6F00 6300 7300  ........D.o.c.s.
5C00 4900 6E00 7300 7400 6100 6C00 6C00  .I.n.s.t.a.l.l.
6100 7400 6900 6F00 6E00 2000 4700 7500  a.t.i.o.n. .G.u.
6900 6400 6500 2E00 6400 6F00 6300 7800  i.d.e...d.o.c.x.
0000 0000 1000 0400 0000 0000 0000 0000  ................
4D78 4163 0000 0000  MxAc....

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 73
FE53 4D42 4000 0100 4300 00C0 0500 0000  .SMB@...C.......
0300 0000 0000 0000 A500 0000 0000 0000  ................
2500 0800 0000 0000 7500 0000 0004 0000  %.......u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 0000 0000 00 .........

undefined
console.trace()
FAILED
TaskQueue: consumeTask - queue: empty
Unchecked runtime.lastError while running notifications.create: Some of the required properties are missing: type, iconUrl, title and message.
    at Object.showNotification (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:18440:30)
    at Object.handleError (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:18434:30)
    at Object.cifsClient.writeFile.onError (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:17986:33)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:18718:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:16427:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:16886:13)
TaskQueue: addTask - Call consume task: length=1
TaskQueue: consumeTask - execute task: length=1
onCloseFileRequested Object {fileSystemId: "cifsfs://WAN-MON01:445/WANCASTLE@SMBDomainUser/Public", openRequestId: 287, requestId: 289}
TaskQueue: consumeTask - queue: empty
TaskQueue: addTask - Call consume task: length=1
TaskQueue: consumeTask - execute task: length=1
onReadDirectoryRequested Object {directoryPath: "/", fileSystemId: "cifsfs://WAN-MON01:445/WANCASTLE@SMBDomainUser/Public", requestId: 290}
Client#readDirectory: \
Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
CreateRequest {types_: Types, structureSize_: 57, requestedOplockLevel_: 0, impersonationLevel_: 2, desiredAccess_: 1048705…}
Packet {types_: Types, data_: ArrayBuffer, dataLength_: 144, packetHelper_: PacketHelper}
writePacket
FE53 4D42 4000 0100 0000 0000 0500 0100  .SMB@...........
0000 0000 0000 0000 A700 0000 0000 0000  ................
0100 0000 0100 0000 7500 0000 0004 0000  ........u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
3900 0000 0200 0000 0000 0000 0000 0000  9...............
0000 0000 0000 0000 8100 1000 1000 0000  ................
0700 0000 0100 0000 0100 0000 7800 0000  ............x...
7800 0000 1800 0000 0000 0000 1000 0400  x...............
0000 0000 0000 0000 4D78 4163 0000 0000  ........MxAc....

readPacket
_readPacketSize
_readPacketSize - 2
readPacket: 73
FE53 4D42 4000 0100 0301 0000 0500 0100  .SMB@...........
0300 0000 0000 0000 A600 0000 0000 0000  ................
2900 0800 0000 0000 7500 0000 0004 0000  ).......u.......
0000 0000 0000 0000 0000 0000 0000 0000  ................
0900 0000 0000 0000 00 .........

103: UNKNOWN
console.trace()
FAILED
TaskQueue: consumeTask - queue: empty

**Comment by AndreyLavrov** [comment]
103: Unknown error rised by background.js 6400 line:

![fs4w](https://cloud.githubusercontent.com/assets/12710354/10722311/de32b2d8-7bbf-11e5-9c89-ec7fa40787cc.png)
