### ISSUE TITLE
1.50 net::ERR_CONNECTION_TIMED_OUT no IP traffic to PC

### ISSUE THREAD

**Issue by cottonwool** [yoichiro/chromeos-filesystem-cifs#90]
Despite 1.50 seeming to connect very well at times it has also consistently failed to connect at times.

Unlike a previous similar problem in this case there is no observable SMB IP traffic between the chromebook and the PC. This was tested by capturing at the PC and at the intervening router (a Fritz! Box which supports packet capture).

I can ping between the two machines and observe the ICMP packets but there is no evidence of other traffic between the two IP addresses or traffic to port 445 on the PC.

Most of the time when there is no connection  and net::ERR_CONNECTION_TIMED_OUT
then the only output from the console is 

background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect

e.g

Console
Looked up with chrome.mdns:  Array[0]length: 0__proto__: Array[0]concat: concat()constructor: Array()entries: entries()every: every()filter: filter()forEach: forEach()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()Symbol(Symbol.iterator): ArrayValues()Symbol(Symbol.unscopables): ObjectcopyWithin: trueentries: truefill: truefind: truefindIndex: truekeys: true__proto__: Object__defineGetter__: **defineGetter**()**defineSetter**: **defineSetter**()**lookupGetter**: **lookupGetter**()**lookupSetter**: **lookupSetter**()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get **proto**: get **proto**()set **proto**: set **proto**()
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect

But then after a series of attempts an exception occurred (see below)

background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
extensions::uncaught_exception_handler:8 Error in response to sockets.tcp.connect: Error: Attempting to use a disconnected port object
    at chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14287:17
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13246:25)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14013:25)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12024:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12365:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11519:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11801:32)handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:72
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect

This is when trying to connect to shares on a Win 7 Ultimate PC.

![screenshot 2015-08-12 at 17 51 11](https://cloud.githubusercontent.com/assets/8496854/9230603/0b1cedde-411b-11e5-8513-4a997a2efba5.png)

**Comment by cottonwool** [comment]
I have now found two problems with my set-up.
1. After a recent Windows update the Windows workgroup seems to have been turned off.
2. The Kaspersky firewall software on the Win 7 PC seems to block SMB traffic sometimes.

I have now re-enabled the Windows workgroup and checked the shares are in place.
I have configured the firewall to recognise the local network by subnet as local network where file sharing can be allowed.
I am testing the shares on my Win 7 PC from my Ubuntu 15.04 PC.
I can now see SMB packets on port 445 at my PC .
I can see things happening on the trace that seem to be associated with when playing a music file fails.

I should close this bug and open a new one for the exception seen and for the errors when playing a music file stops unexpectedly.
