### ISSUE TITLE
uncaught_exception_handler:8 Error in response to sockets.tcp.connect: 

### ISSUE THREAD

**Issue by cottonwool** [yoichiro/chromeos-filesystem-cifs#91]
In the situation where my firewall or some other reason was blocking connections and I was getting repeated occurrences of 
net::ERR_CONNECTION_TIMED_OUT

The extension threw an exception.

This has happened only once.

background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect
extensions::uncaught_exception_handler:8 Error in response to sockets.tcp.connect: Error: Attempting to use a disconnected port object
at chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14287:17
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:13246:25)
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14013:25)
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12024:13)
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12365:13)
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11519:13)
at null. (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11801:32)handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:72
background.js:6176 Domain name not specified. '?' will be applied.
background.js:6169 connect

![screenshot 2015-08-12 at 17 51 11](https://cloud.githubusercontent.com/assets/8496854/9256561/0fbaa49e-41e8-11e5-9b02-e326c64e4ca4.png)

**Comment by yoichiro** [comment]
@cottonwool I have a question. Was the notification you faced shown many times at the same time?

**Comment by yoichiro** [comment]
I close this issue, because I could not get more information from the reporter. Sorry.
